### ISSUE TITLE
Fpscrashdestroyer thingy 

### ISSUE THREAD

**Issue by ZeMumRu** [joeengo/Future#3]
If you could please explain the function of the fpscrash thingy and how to do it. I mean is it supposed to make my fps also low? Also are we just supposed to hold the shield then activate fpscrash thingy? Just answer these questions. Keep up the good work!!

**Comment by joeengo** [comment]
> If you could please explain the function of the fpscrash thingy and how to do it. I mean is it supposed to make my fps also low? Also are we just supposed to hold the shield then activate fpscrash thingy? Just answer these questions. Keep up the good work!!

To use it, you are not suppose to click your mouse at all. your fps will lower while it is making new threads.
steps:
1. when in lobby equip shielder kit
2. go in game and wait til u get shield
3. hold shield and enable crasher
4. wait until your ping goes above 10k

**Comment by ZeMumRu** [comment]
"hold shield and enable crasher"

**Comment by ZeMumRu** [comment]
Also is it going to crash me too?
